services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: employee-management-app
    ports:
      - "8080:8080"
    environment:
      - ACTIVE_PROFILE=dev
      - DB_URL=jdbc:postgresql://db:5432/ebuka
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=ebuka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ management UI

volumes:
  db-data:
